package com.capstone.jobmatch.utills

object KeySkills {
    val skillsArray: Array<String> = arrayOf(
            "Key Skills",
            "Media Planning",
            "pre sales",
            "Computer science",
            "Technical Support",
            "manual testing",
            "adobe experience manager",
            "channel partners",
            "TFS",
            "secretary",
            "website",
            "operations",
            "Oracle IDAM",
            "digital marketing",
            "instrumentation engineering",
            "Report Generation",
            "Copyright",
            "C#",
            "sales manager",
            "lead generation",
            "contract management",
            "QA Executive",
            "Java EE",
            "Conceptualization",
            "Articulate Storyline",
            "Area Sales Management",
            "qmail",
            "Java",
            "GIS",
            "Administration",
            "filing",
            "Outbound",
            "Troubleshooting",
            "4G",
            "JMS",
            "market",
            "fixed assets",
            "Team management",
            "Commercial Activities",
            "ODI",
            "javascript",
            "Relationship management",
            "android",
            "cca",
            "bca",
            "Accounting",
            "networking",
            "Automobile",
            "Tourism",
            "PHP",
            "Chief Engineer",
            "WebLogic",
            "Service level",
            "Graphics",
            "Sales",
            "sds",
            "Market analysis",
            "ERP",
            "revenue generation",
            "co ordination",
            "English",
            "cloud",
            "National",
            "Mentor",
            "Performance Testing",
            "Pivot Table",
            "international bpo",
            "Innovative",
            "Communication Skills",
            "design",
            "Technical Writing",
            "Product placement",
            "Management accounting",
            "Trade",
            "XML",
            "zld",
            "Analyst",
            "Intern",
            "C",
            "CSS",
            "Business Development Management",
            "Ethical Hacking",
            "Graphic designing",
            "Payment collection",
            "Internship",
            "market penetration",
            "jquery",
            "technical recruitment",
            "Front Office Executive",
            "Project Administration",
            "Order Management system",
            "analytical",
            "NCTVT",
            "Drupal",
            "AutoCAD",
            "Automation Engineer",
            "Revenue Cycle Management",
            "Voice process",
            "Predictive Modeling",
            "molecular biology",
            "accounts executive",
            "Informatica Power Center",
            "Validation",
            "Forecasting",
            "Pay Per Click",
            "marketing officer",
            "Project management",
            "PR",
            "counselling",
            "Help Desk",
            "asp dot net",
            "Secondary Research",
            "Teaching",
            "X - Ray",
            "cms",
            "C#",
            "Escalation management",
            "planning",
            "customer support",
            "Senior Design Engineer",
            "Technical Support Executive",
            "Data analysis",
            "Detail Design",
            "assistant restaurant manager",
            "layout",
            "selling",
            "photoshop",
            "Python",
            "server",
            "Senior management",
            "QA",
            "Testing",
            "assembly language",
            "Product management",
            "ajax",
            "customer service",
            "Oracle",
            "MS Office",
            "Customer relationship",
            "Unix",
            "Merchandising",
            "Computer Operator",
            "operations management",
            "Customer Support Executive",
            "Staff Training",
            "process",
            "digital marketing",
            "Illustrator",
            "Technical Architecture",
            "Layout design",
            "Bpo Voice",
            "HTML5",
            "Product training",
            "Customer profitability",
            "Stores",
            "BPO",
            "Linux",
            "Credit Officers",
            "Balance Sheet Finalisation",
            "accounts payable",
            "Change management",
            "Business communication",
            "Usage",
            "salesforce",
            "Execution",
            "Recruitment",
            "Excel",
            "Production Management",
            "Digital media",
            "Motion Graphics",
            "Tally",
            "Financial reporting",
            "NSE",
            "MySQL",
            "MIS reporting",
            "soa",
            "Art Director",
            "fresher",
            "single sign - on",
            "coding",
            "accent",
            "business development",
            "marketing executive",
            "fundraising",
            "worldspan",
            "Front end",
            "CVS",
            "Asp.Net MVC",
            "Loans",
            "Angularjs",
            "Sales Engineering",
            "Design Development",
            "NAV calculation",
            "hiring",
            "pharmaceutical",
            "mechanical operation",
            "Renewable energy",
            "Sales Associate",
            "MCSE",
            "SSRS",
            "GIT",
            "GNM",
            "institutions",
            "Recruitment",
            "financial analysis",
            "Publishing",
            "Auditing",
            "c++",
            "rest",
            "Process automation",
            "IT Sales",
            "Sales Executive",
            "Web development",
            "clinical pharmacy",
            "sap",
            "academic research",
            "marketing",
            "RT",
            "Equipment Maintenance",
            "motor insurance",
            "SQL",
            "CATIA",
            "Outbound Sales",
            "financial s",
            "Hardware Board Design",
            "environment",
            "Screening",
            "Retail Sales",
            "J2Ee",
            "Android Development",
            "Counselor",
            "Wireless",
            "hr",
            "Associate",
            "Receptionist",
            "QMS",
            "spring boot",
            "Dynamics CRM",
            "Marketing Strategy",
            "O2C",
            "visualization",
            "pnr",
            "Assistant Manager Purchase",
            "SQL",
            "IIS",
            "pharma chemicals",
            "Hibernate",
            "Exadata",
            "hospital",
            "Training Needs",
            "Real Estate Construction",
            "project support",
            "Procurement",
            "Leadership training",
            "Camel_magarpatta",
            "customer profiling",
            "customer segmentation",
            "Negotiation",
            "Fire Safety",
            "Installation",
            "dot matrix",
            "Reporting",
            "us it recruiter",
            "service engineering",
            "enterprise sales",
            "inbound",
            "Monthly Reports",
            "kaggle",
            "Talent Acquisition",
            "Retail",
            "Manager Sales",
            "land acquisition",
            "cnc",
            "Medical Representative",
            "Sales Engineer",
            "Inside Sales",
            "Customer Care",
            "Performance management",
            "Service delivery",
            "laundry",
            "TDS",
            "T-SQL",
            "Audit",
            "gsm",
            "Fortigate",
            "HVAC",
            "electronic trading",
            "Product management",
            "Sales Head",
            "Com",
            "Network",
            "Equity",
            "Salesforce Developer",
            "SAP PLM",
            "Microstrategy",
            "asp.net",
            "Presales",
            "Editing",
            "set",
            "Nursing",
            "back office processing",
            "shares",
            "Interpersonal skills",
            "Analytical skills",
            "Mba Finance",
            "Technical Management",
            "Oracle database",
            "Business solutions",
            "Accounting Entries",
            "Sql Server 2008",
            "Architect",
            "access controls",
            "oracle sales",
            "microsoft dynamics ax"
    )

    val arraySortByName = skillsArray.sortedArray()
}